version: '2'

services:

  fitbit_googlefit:
    container_name: fitbit_googlefit
    image: puzza007/fitbit_googlefit:latest
    restart: always
    volumes:
      - ./config:/config
    environment:
      - 'TZ=Pacific/Auckland'
      - 'PGID=1000'
      - 'PUID=1000'
